### PR TITLE
Include lua stacktrace when LuaError is thrown

### PR DESCRIPTION
**Pull request by aaiyer**

### CODE REVIEW

**Comment by aaiyer** [comment]
Tavis CI failed because of the latest Cython not supporting Python 3.3. The changes passed Travis on all other configured Python+Lua versions.

**Comment by kmike** [comment]
Could you please add a test case for this feature?
Does it work if debug module is disabled, e.g. by a sandbox?

**Comment by aaiyer** [comment]
@kmike Yes, it works if debug is disable

**Comment by aaiyer** [comment]
Added unit test

**Comment by scoder** [comment]
Looks good to me, thanks! (I'll fix the Py2.6 errors in the test.)

**Pull request merged**
